---

- ansible.builtin.uri:
    url: "https://{{ githoster_api }}/orgs/{{ repo_owner }}/actions/variables"
    method: "POST"
    body:
      name: "{{ secret_name }}"
      value: "{{ secret_value }}"
      visibility: "{{ secret_visibility }}"
    body_format: "json"
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ request_bearer }}"
      X-GitHub-Api-Version: "{{ githoster_api_version }}"
    status_code: "{{ range(200, 300) | list }}"
  register: githoster_create_secret_response
