---

- ansible.builtin.set_fact:
    page: 1
    responses:
      json:
        variables: []

- ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/git-hoster/secret/_get.yml"

- ansible.builtin.set_fact:
    responses:
      json:
        variables: "{{ responses.json.variables + [{'name': secret_name, 'value': ''}] }}"
- ansible.builtin.set_fact:
    githoster_get_secret: "{{ (responses.json.variables | selectattr('name', '==', secret_name) | list | first).value }}"
