---

- ansible.builtin.uri:
    url: "https://{{ githoster_api }}/orgs/{{ repo_owner }}/repos?{{ query_parameters | dict2items | map(attribute='key') | zip(query_parameters | dict2items | map(attribute='value', default='') | map('urlencode')) | map('join', '=') | join('&') }}"
    method: "GET"
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ request_bearer }}"
      X-GitHub-Api-Version: "{{ githoster_api_version }}"
    status_code: "{{ range(200, 300) | list }}"
  register: response
  vars:
    query_parameters:
      page: "{{ page }}"
      per_page: 100
      type: 'all'

- ansible.builtin.set_fact:
    page: "{{ page + 1 }}"
    responses:
      json: "{{ (responses.json | default([])) + response.json }}"

- when: response.json | length > 0
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/git-hoster/repository/_created.yml"
