---

- ansible.builtin.uri:
    url: "https://{{ githoster_api }}/repos/{{ issue_repo }}/issues"
    method: "POST"
    body:
      title: "{{ issue_title }}"
    body_format: "json"
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ request_bearer }}"
      X-GitHub-Api-Version: "{{ githoster_api_version }}"
    status_code: "{{ range(200, 300) | list }}"
  register: githoster_create_issue_response
