name: clear-history
on:
  workflow_dispatch:

jobs:
  delete-old-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "main"
        fetch-depth: 0
        submodules: "true"
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
    - uses: yanovation/delete-old-actions@v1
      with:
        days-ago: 0
        token: "${{ vars.BOT_GITHUB_TOKEN }}"
