name: secrets-reencrypt
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  secrets-reencrypt:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-reencrypt"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
