name: secrets-rotate
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  secrets-rotate:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-rotate"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
