name: secrets-cherrypick
on:
  workflow_dispatch:
    inputs:
      CHERRYPICK_COMMIT:
        type: string
        description: 'CHERRYPICK_COMMIT: commit to cherry-pick'
        required: true

permissions:
  contents: write

jobs:
  secrets-cherrypick:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-git"
      playbook_extravar_secrets_git_cmdargs: "cherry-pick -x ${{ github.event.inputs.CHERRYPICK_COMMIT }}"
      playbook_extravar_secrets_git_push: "true"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
