name: secrets-revert
on:
  workflow_dispatch:
    inputs:
      REVERT_COMMIT:
        type: string
        description: 'REVERT_COMMIT: commit to cherry-pick'
        required: true

permissions:
  contents: write

jobs:
  secrets-revert:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-git"
      playbook_extravar_secrets_git_cmdargs: "revert --no-edit ${{ github.event.inputs.REVERT_COMMIT }}"
      playbook_extravar_secrets_git_push: "true"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
