name: secrets-export
on:
  workflow_dispatch:
    inputs:
      EXPORT_CONFIRM:
        type: string
        description: 'EXPORT_CONFIRM: Type "yes" if you really want to export the GnuGP keys'
        required: true

permissions:
  contents: write

jobs:
  secrets-export:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-export"
      playbook_extravar_secrets_export_confirm: "${{ github.event.inputs.EXPORT_CONFIRM }}"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
