name: secrets-copy
on:
  workflow_dispatch:
    inputs:
      COPY_OLDPATH:
        type: string
        description: 'COPY_OLDPATH: password or directory to copy'
        required: true
      COPY_NEWPATH:
        type: string
        description: 'COPY_NEWPATH: password or directory destination'
        required: true

permissions:
  contents: write

jobs:
  secrets-copy:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-copy"
      playbook_extravar_secrets_copy_oldpath: "${{ github.event.inputs.COPY_OLDPATH }}"
      playbook_extravar_secrets_copy_newpath: "${{ github.event.inputs.COPY_NEWPATH }}"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
