name: secrets-gen
on:
  workflow_dispatch:
    inputs:
      GEN_PATH:
        type: string
        description: 'GEN_PATH: path to the password to generate'
        required: true
      GEN_LEN:
        type: number
        description: 'GEN_LEN: length of the password to generate'
        default: 24
        required: false

permissions:
  contents: write

jobs:
  secrets-gen:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-gen"
      playbook_extravar_secrets_gen_path: "${{ github.event.inputs.GEN_PATH }}"
      playbook_extravar_secrets_gen_len: "${{ github.event.inputs.GEN_LEN }}"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
