name: secrets-edit
on:
  workflow_dispatch:
    inputs:
      EDIT_PATH:
        type: string
        description: 'EDIT_PATH: path to the existing password'
        required: true
      EDIT_PASSWORD:
        type: string
        description: 'EDIT_PASSWORD: password to insert'
        required: true

permissions:
  contents: write

jobs:
  secrets-edit:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-edit"
      playbook_extravar_secrets_edit_path: "${{ github.event.inputs.EDIT_PATH }}"
      playbook_extravar_secrets_edit_password: "${{ github.event.inputs.EDIT_PASSWORD }}"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
