name: secrets-del
on:
  workflow_dispatch:
    inputs:
      DEL_PATH:
        type: string
        description: 'DEL_PATH: path to the password to remove'
        required: true

permissions:
  contents: write

jobs:
  secrets-del:
    uses: tiawl-lab/demo/.github/workflows/common.yml@main
    with:
      playbook_tag: "secrets-del"
      playbook_extravar_secrets_del_path: "${{ github.event.inputs.DEL_PATH }}"
      gh_token: "${{ vars.BOT_GITHUB_TOKEN }}"
